### ISSUE TITLE
Error: Cannot find module 'babel-plugin-inline-json-import'

### ISSUE THREAD

**Issue by yonc** [liferay/liferay-js-toolkit#446]
I don't know why `liferay-npm-bundler` version 2.14.0 build error. It used to work on version 2.13.2
**package.json**
```
{
	"dependencies": {
		"vue": "^2.0.0",
		"vue-tel-input": "^2.5.0"
	},
	"devDependencies": {
		"babel-cli": "6.26.0",
		"babel-plugin-inline-json-import": "0.3.2",
		"babel-preset-env": "1.7.0",
		"liferay-npm-bundler": "^2.0.0"
	},
	"name": "cw-vuejs-provider",
	"scripts": {
		"build": "liferay-npm-bundler"
	},
	"version": "1.0.0"
}

```
**.babelrc**
```
{
	"presets": ["env"]
}
```
**.npmbundlerrc**
```
{
    "dump-report": true,
    "exclude": {
        "vue": ["src/**/*"],
        "libphonenumber-js": ["source/**/*", "bin/**/*", "bundle/**/*"],
        "resolve": true
    },
    "process-serially" :true,
    "packages": {
        "libphonenumber-js": {
            ".babelrc": {
                "plugins": [["inline-json-import", {}]],
                "presets": ["liferay-standard"]
            }
        },
        "debug": {
            ".babelrc": {
                "comments": false,
                "presets": ["liferay-standard", "env"]
            }
        }
    }
}

```

**Error Log**
```
 liferay-npm-bundler



Error: Cannot find module 'babel-plugin-inline-json-import,[object Object]' from '/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/liferay-npm-bundler-preset-standard'
    at Function.module.exports [as sync] (/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/resolve/lib/sync.js:74:15)
    at Project.toolResolve (/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/liferay-npm-build-tools-common/lib/project/index.js:258:46)
    at Project.toolRequire (/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/liferay-npm-build-tools-common/lib/project/index.js:244:29)
    at concat.concat.plugins.map.plugin (/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/liferay-npm-build-tools-common/lib/project/transform.js:117:41)
    at Array.map (<anonymous>)
    at Transform.getBabelPlugins (/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/liferay-npm-build-tools-common/lib/project/transform.js:111:32)
    at babelifyPackage (/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/liferay-npm-bundler/lib/steps/transform.js:121:55)
    at runBundlerPlugins.then (/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/liferay-npm-bundler/lib/steps/transform.js:60:21)
    at <anonymous>


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cw-vuejs-provider@1.0.0 build: `liferay-npm-bundler`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cw-vuejs-provider@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yonc/.npm/_logs/2019-10-30T06_27_21_837Z-debug.log

> Task :modules:apps:cw-vuejs-provider:npmRunBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:apps:cw-vuejs-provider:npmRunBuild'.
> Process 'command '/home/yonc/dev/crosswired-common/.nodejs/node_modules/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s
30 actionable tasks: 6 executed, 24 up-to-date

```
**2019-10-30T06_27_21_837Z-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/yonc/dev/crosswired-common/.nodejs/node_modules/bin/node',
1 verbose cli   '/home/yonc/dev/crosswired-common/.nodejs/node_modules/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'build',
1 verbose cli   '--loglevel',
1 verbose cli   'warn',
1 verbose cli   '--production',
1 verbose cli   'false',
1 verbose cli   '--progress',
1 verbose cli   'true' ]
2 info using npm@5.7.1
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle cw-vuejs-provider@1.0.0~prebuild: cw-vuejs-provider@1.0.0
6 info lifecycle cw-vuejs-provider@1.0.0~build: cw-vuejs-provider@1.0.0
7 verbose lifecycle cw-vuejs-provider@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle cw-vuejs-provider@1.0.0~build: PATH: /home/yonc/dev/crosswired-common/.nodejs/node_modules/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider/node_modules/.bin:/home/yonc/dev/crosswired-common/.nodejs/node_modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/usr/local/bin
9 verbose lifecycle cw-vuejs-provider@1.0.0~build: CWD: /home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider
10 silly lifecycle cw-vuejs-provider@1.0.0~build: Args: [ '-c', 'liferay-npm-bundler' ]
11 silly lifecycle cw-vuejs-provider@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle cw-vuejs-provider@1.0.0~build: Failed to exec build script
13 verbose stack Error: cw-vuejs-provider@1.0.0 build: `liferay-npm-bundler`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/yonc/dev/crosswired-common/.nodejs/node_modules/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/yonc/dev/crosswired-common/.nodejs/node_modules/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cw-vuejs-provider@1.0.0
15 verbose cwd /home/yonc/dev/crosswired-common/modules/apps/cw-vuejs-provider
16 verbose Linux 5.0.0-32-generic
17 verbose argv "/home/yonc/dev/crosswired-common/.nodejs/node_modules/bin/node" "/home/yonc/dev/crosswired-common/.nodejs/node_modules/lib/node_modules/npm/bin/npm-cli.js" "run-script" "build" "--loglevel" "warn" "--production" "false" "--progress" "true"
18 verbose node v8.10.0
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error cw-vuejs-provider@1.0.0 build: `liferay-npm-bundler`
22 error Exit status 1
23 error Failed at the cw-vuejs-provider@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
